# charts/myapp/templates/backend-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  labels:
    app: backend
type: Opaque
data:
  # Base64 Encode של הערכים מ-values.yaml
  postgres-user: {{ .Values.backend.secrets.DB_USER | b64enc | quote }}
  postgres-password: {{ .Values.backend.secrets.DB_PASSWORD | b64enc | quote }}