# charts/myapp/templates/postgres-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }} #  my-postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432       # 驻专 砖-Service 砖祝 爪 (转 拽住专)
      targetPort: 5432 # 驻专 砖拽专 砖 PostgreSQL  
      protocol: TCP
  selector:
    app: postgres # 驻 驻 注 转转 'postgres'