global:
  # 拽爪 专驻 (Scrape) 专专转 
  scrape_interval: 15s 

scrape_configs:
  # 1. Job: 专 Prometheus 注爪
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Job: 专 砖专转 -Backend (FastAPI)
  - job_name: 'backend'
    #  Prometheus 砖 砖 砖专转 'backend' 转 专砖转 -Docker
    static_configs:
      - targets: ['backend:8000'] 
    # 转 砖砖驻转 -FastAPI (main.py: app.mount("/metrics", metrics_app))
    metrics_path: '/metrics'